# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 15:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_feature_number', models.IntegerField()),
                ('feature', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('pop_range', models.CharField(max_length=128)),
                ('population_2000', models.IntegerField()),
                ('fips_5', models.IntegerField()),
                ('county', models.CharField(max_length=64)),
                ('county_fips', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('state_fips', models.IntegerField()),
                ('display', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
